version: '3.8'
services:
  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
